<?php

namespace NSEPBundle\Repository;

/**
 * TestcaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestcaseRepository extends \Doctrine\ORM\EntityRepository
{
}
